inherit_from:
  - https://shopify.github.io/ruby-style-guide/rubocop.yml

require:
  - ./lib/statsd/instrument/rubocop.rb

AllCops:
  TargetRubyVersion: 2.3
  UseCache: true
  CacheRootDirectory: tmp/rubocop
  Exclude:
    - statsd-instrument.gemspec

Naming/FileName:
  Enabled: true
  Exclude:
    - lib/statsd-instrument.rb

Style/ClassAndModuleChildren:
  Enabled: false # TODO: enable later

# Enable our own cops on our own repo

StatsD/MetricReturnValue:
  Enabled: true

StatsD/MetricValueKeywordArgument:
  Enabled: true

StatsD/PositionalArguments:
  Enabled: true

StatsD/SplatArguments:
  Enabled: true

StatsD/MetaprogrammingPositionalArguments:
  Enabled: true

StatsD/MeasureAsDistArgument:
  Enabled: true

StatsD/MetricPrefixArgument:
  Enabled: true
